name: password_manager
description: A terminal-based password manager.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

# Add regular dependencies here.
dependencies:
  cryptography: ^2.7.0
  #pointycastle: ^4.0.0
  #convert: ^3.1.2
  #crypto: ^3.0.3
  # path: ^1.8.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
